### ISSUE TITLE
Editing the file .json in regular notepad causes a root mismatch

### ISSUE THREAD

**Issue by Victuz** [tracktwo/xcomsave#10]
Editing the .json file in notepad in any fashion (changing one value) causes a root mismatch. Editing the same values in notepad++ for example didn't cause that problem. I recommend putting a disclaimer on the readme.

Windows 7

**Comment by tracktwo** [comment]
I can't repro this, are you maybe using a non-english save or windows locale? The file is written in utf-8, which notepad likely can't handle well if you're using a non-english save.

**Comment by Victuz** [comment]
The save is international, my system locale is polish an so is the setting for non-unicode programs. that is probably the cause.

Not using standard notepad worked just fine as I said, hence my recommendation of noting it.
