### ISSUE TITLE
The tool fails on input file path containing spaces

### ISSUE THREAD

**Issue by the-vindicar** [tracktwo/xcomsave#17]
If I put the tool and the save file next to each other, and run 
`xcom2json save4`
it works fine.
If I provide it with full pathm like this
`xcom2json "D:\Path with spaces\save4"`
It fails to do so, despite double quotes being standart way to escape spaces in command line arguments.

**Comment by liutieguan** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2297	'<': illegal, right operand has type 'const T'	json2xcom	C:\xcomsave-master\json11\json11.cpp	157	


Severity	Code	Description	Project	File	Line	Suppression State
Error	C2296	'<': illegal, left operand has type 'const T'	json2xcom	C:\xcomsave-master\json11\json11.cpp	157	

    bool equals(const JsonValue* other) const override {
        return m_value == static_cast<const Value<tag, T>*>(other)->m_value;
    }
    bool less(const JsonValue* other) const override {
        return m_value < static_cast<const Value<tag, T>*>(other)->m_value;
    }

errors come. cant build jason to save

**Comment by tracktwo** [comment]
Paths with spaces now work, and the unrelated json build error has been fixed by updating to a more recent version of json11.
