### ISSUE TITLE
Error: unsupported version: 15

### ISSUE THREAD

**Issue by glassneedles** [tracktwo/xcomsave#19]
When I try to use this tool I get that error. I've checked this on all save games I have for the game a majority of which are in the strategy part of the game. I've attached one save game that exhibits this.
[save12.zip](https://github.com/tracktwo/xcomsave/files/4997674/save12.zip)

**Comment by tracktwo** [comment]
Thanks for the report. Version 15 is Enemy Unknown, which was contributed by someone else but apparently was missing a small part of the code needed for support or was broken by the Android support. I've added this and it looks like it decompresses the file correctly now. Please try the new 1.8 release.

**Comment by glassneedles** [comment]
I really appreciate the insanely quick turn around on that (seriously I was expecting to wait a while for it to be looked at yet alone fixed) and that does fix the issue. However I get the same error when converting back to xcom. I only edited the head value of 2 of my units as I somehow ended up with the value at 0 which resulted in headless squad members and unable to be changed in the game.

I have verified that I changed the value inline with how it appeared on other squad members. If you do a search for Max and Adam in the json file those are the only ones I edited and the only change was the ihead value changing from 0 to 1. 

[xcomsave-1.8.zip](https://github.com/tracktwo/xcomsave/files/5001780/xcomsave-1.8.zip)

**Comment by tracktwo** [comment]
Hah sorry about that. That'll teach me to upload a release in a hurry without fully testing it :) I'll fix the other direction tonight.

**Comment by glassneedles** [comment]
No problem! I actually had a go at fixing it myself after forking it. Haven't built it yet but am in the process. I'm not expecting it to actually work since I am a student and haven't written anything in C++ before. Thankfully got a fair amount of experience with Java so it's still fairly readable! 

Will let you know if it works.

**Comment by glassneedles** [comment]
Ok the build aspect massively failed. I cloned the repo and tried to build it using the cmake integration into visual studio 17. I got 5-6 errors in files I hadn't touched and I don't know enough C++ or about json files to try and figure out what went wrong with it.

**Comment by tracktwo** [comment]
Did you clone recursively? The errors might be due to missing headers for the dependencies if not. At any rate, I've updated version 1.8.1 and at least verified that it could rebuild a save file. I don't have EU/EW installed on this machine so I didn't try to actually load the save, though. Let me know if you have any problems loading a modified save.
