### ISSUE TITLE
XCOM:EU support

### ISSUE THREAD

**Issue by golinski** [tracktwo/xcomsave#2]
I am trying to add support for the vanilla XCOM:EU files (version in header: 15). Are there any resources I could find useful in understanding the binary format? Or maybe the only solution is reverse engineering? Your code is very enlightening, but hopefully you can point me to other resources.

**Comment by tracktwo** [comment]
I haven't found any documentation about the format, unfortunately. The contents of this project are what I managed to learn from this project by Kelnor277: https://github.com/Kelnor277/Xcom2012SoldierViewer plus what I've reverse engineered myself. If you're looking at geoscape saves I can't imagine the format has changed that much between EU and EW, but I could be wrong. Tactical saves are a whole different beast and I've not figured out how to even parse them, nevermind interpret the data correctly.

**Comment by Patola** [comment]
I am also interested in this. Tried to use xcom2json on a tactical savegame from Linux XCOM: UE and this is what I got:
```
[2:05] [3666] [patola@ovo build]% ./xcom2json save36 
Error: Data does not appear to be an xcom save: expected file version 16 but got 15
Error (0x0000002e): Malformed actor table entry: missing 0 instance
```

Also tried to decompress it to see if it would work, but it did not - it seems this software is prepared to automatically decompress the savegames, right?

**Comment by tracktwo** [comment]
It does handle the decompression, yes. But unless golinski has made any progress in reverse engineering the EU file format I suppose it isn't as simple as just checking for the slightly older version number, unfortunately.

**Comment by golinski** [comment]
[At my repo](https://github.com/golinski/xcomsave/tree/enemy-unknown) you can find a branch that has support for EU. Changes are not big, but scattered throughout the code, and I have not tried to integrate into the codebase and make a pull request.

**Comment by tracktwo** [comment]
Great stuff! I'll add a link to your repo to the main page. If you ever get around to submitting it as a PR I'll definitely include it!

**Comment by Anders1232** [comment]
I made the PR #14 with the merge. Hope works nicely.

**Comment by tracktwo** [comment]
Thanks!
