### ISSUE TITLE
Output.dat file

### ISSUE THREAD

**Issue by DM-666** [tracktwo/xcomsave#3]
xcom2json.exe version 1.2 creating an output.dat file in working directory, which can be 40+ mb. While its not a big deal, but still. Isn't it a temporary file which should be deleted after program ends?

**Comment by tracktwo** [comment]
It's a file I dumped out for debugging purposes, it's not really necessary at all. It basically just contains the uncompressed save data. I can put that under a switch.

**Comment by DM-666** [comment]
Yes, that looks a best solution to me.

**Comment by tracktwo** [comment]
Updated release 1.4 to remove this. The output.dat file will only be generated in debug builds now. I've added a new set of binaries to the release tab, and these are built in release mode so you shouldn't see the file anymore.

**Comment by DM-666** [comment]
Thanks a million!
