### ISSUE TITLE
Doesnt work with the russian version of the game

### ISSUE THREAD

**Issue by roboserg** [tracktwo/xcomsave#6]
```
D:\xcomjson_windows_1.4>xcom2json.exe save1
Error (0x0000008c): Found UTF-16 string in unexpected location
```

Could be that I have the latest version of the game, or because the save is from a Russian localization.

**Comment by tracktwo** [comment]
I'd guess it's probably because of the localization. If you can get me a link to the save I can try to fix it.

**Comment by roboserg** [comment]
That would be awesome! Here is the file - http://puu.sh/sxqsR/5a62e40032

I even tried to switch the language of the game, but then the game doesnt want to load the save file, saying "the save file is from different language of the game". I have steam version of the game, with the latest patches.

**Comment by tracktwo** [comment]
I've just uploaded version 1.5, and I successfully converted your save with this version. This should now have much better support for non-Roman languages.

**Comment by roboserg** [comment]
Wow, thank you very much, it works!
