### ISSUE TITLE
Getting: Error (0x00220fb6): read_string found an invalid string length.

### ISSUE THREAD

**Issue by tharbad08** [tracktwo/xcomsave#9]
[save74.zip](https://github.com/tracktwo/xcomsave/files/1135585/save74.zip)

Ideas? 

Tried to rebuild just in case. I think save file structure was changed.

Attached save file (Zipped due to github policy)

**Comment by tracktwo** [comment]
This is a tactical save - currently I don't know how to handle reading tactical saves, just geoscape saves. Could certainly use a better error message than just crashing though :)

**Comment by tharbad08** [comment]
"Error (0x00220fb6): read_string found an invalid string length" is all i got.
